[SERVICE]
    Flush        5
    Log_Level    info

[INPUT]
    Name          tail
    Path          /logs/app.log
    Tag           py.monitoring
    Read_from_Head true
    DB            /fluent-bit/state/tail.db
    Refresh_Interval 5

[FILTER]
    Name   record_modifier
    Match  *
    Record log_tag py.monitoring

[OUTPUT]
    Name          http
    Match         *
    Host          clickhouse
    Port          8123
    URI           /?query=INSERT+INTO+logs.app_logs+FORMAT+JSONEachRow
    # Change format to json_lines for ClickHouse compatibility
    Format        json_lines
    # Ensure the Content-Type is correct
    header        Content-Type application/x-ndjson
    HTTP_User     fluentbit
    HTTP_Passwd   fluentbitpass
